apiVersion: v1
kind: Secret
metadata:
  name: dagshub-secret
  namespace: default
type: Opaque
stringData:
  MLFLOW_TRACKING_USERNAME: "${DAGSHUB_USERNAME}"
  MLFLOW_TRACKING_PASSWORD: "${DAGSHUB_TOKEN}"
  DAGSHUB_USER_TOKEN: "${DAGSHUB_TOKEN}"
